const catalog=[['project','Projeto','Contexto e objetivo'],['stack','Stack','Tecnologias e arquitetura'],['stack','Database','Dados e persistência'],['feature','Autenticação','Acesso e permissões'],['feature','Pagamentos','Cobrança e assinaturas'],['feature','Dashboard','Visão do produto'],['quality','Security Audit','Auditoria de segurança'],['quality','UI/UX Review','Revisão de experiência'],['quality','Teste Final','Gate de validação'],['control','Loop','Ciclo de melhoria']];
const seed=[['project','Projeto','Contexto e objetivos',70,165,'done','Concluída'],['stack','Stack','Next.js · TypeScript',296,165,'done','Configurada'],['database','Database','Supabase · RLS',522,165,'done','Configurada'],['auth','Autenticação','Login e permissões',522,335,'done','Concluída'],['payments','Pagamentos','Stripe · Assinaturas',748,335,'review','Precisa revisão'],['security','Security Audit','Avaliação de riscos',974,335,'critical','Prioridade ativa'],['ux','UI/UX Review','Interface e acessibilidade',748,505,'review','Aguardando'],['tests','Teste Final','Validação completa',974,505,'review','Aguardando'],['loop','Loop de qualidade','Até score ≥ 90',974,665,'critical','Máx. 3 ciclos']].map(([id,name,desc,x,y,status,statusLabel])=>({id,name,desc,x,y,status,statusLabel}));
let nodes=JSON.parse(localStorage.getItem('mountain-nodes')||'null')||seed,selectedIds=new Set(['security']),selectedId='security',selectedAnnotation,scale=.65,pan={x:16,y:18},drag,marquee,connecting,spaceDown=false,language=localStorage.getItem('mountain-language')||'pt';
const links=[['project','stack','right','left'],['stack','database','right','left'],['database','auth','right','left'],['auth','payments','right','left'],['payments','security','right','left'],['security','tests','right','left'],['ux','tests','right','left'],['tests','loop','right','left'],['loop','security','left','right']],$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem('mountain-nodes',JSON.stringify(nodes)),selected=()=>nodes.find(n=>n.id===selectedId)||nodes[0];
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function library(filter='all',term=''){const holder=$('#library-items');holder.innerHTML='';catalog.filter(x=>(filter==='all'||x[0]===filter)&&`${x[1]} ${x[2]}`.toLowerCase().includes(term.toLowerCase())).forEach(item=>{const el=document.createElement('button');el.className='library-item';el.innerHTML=`<span class="lib-icon"></span><div><strong>${item[1]}</strong><small>${item[2]}</small></div>`;el.onclick=()=>add(item);holder.append(el)})}
function render(){const holder=$('#nodes');holder.innerHTML='';nodes.forEach(node=>{const el=document.createElement('article');el.className=`node ${node.id===selectedId?'selected':''} ${selectedIds.has(node.id)&&node.id!==selectedId?'multi-selected':''} ${node.id==='loop'?'loop-node':''}`;el.dataset.id=node.id;el.style.left=node.x+'px';el.style.top=node.y+'px';const setting=node.loop||{returnTo:'Security Audit',condition:'existirem falhas críticas',max:3},loop=node.id==='loop'?`<div class="loop-details"><span>REPETE PARA</span><b>${setting.returnTo}</b><small>enquanto ${setting.condition} · máx. ${setting.max} ciclos</small></div>`:'';el.innerHTML=`<button class="port in" aria-label="Conectar a ${node.name}"></button><button class="port out" aria-label="Conectar de ${node.name}"></button><div class="node-top"><span class="node-icon"></span><span class="node-more">•••</span></div><h3>${node.name}</h3><p>${node.desc}</p>${loop}<div class="node-status"><i class="${node.status}"></i>${node.statusLabel}</div>`;el.onpointerdown=startNodeDrag;el.onclick=e=>{if(e.shiftKey)select(node.id,true);else if(!selectedIds.has(node.id))select(node.id)};el.querySelectorAll('.port').forEach(port=>port.onpointerdown=startConnection);holder.append(el)});renderEdges();renderMini();$('#node-count').textContent=`${nodes.length} etapas · ${selectedIds.size} selecionada${selectedIds.size===1?'':'s'}`}
function renderEdges(){const svg=$('#edges');svg.innerHTML='';links.forEach(([from,to,fromSide='right',toSide='left'],index)=>{const a=nodes.find(n=>n.id===from),b=nodes.find(n=>n.id===to);if(!a||!b)return;const x1=a.x+(fromSide==='right'?180:0),x2=b.x+(toSide==='right'?180:0),y1=a.y+46,y2=b.y+46,bend=Math.max(70,Math.abs(x2-x1)*.42);const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M ${x1} ${y1} C ${x1+(fromSide==='right'?bend:-bend)} ${y1}, ${x2+(toSide==='left'?-bend:bend)} ${y2}, ${x2} ${y2}`);p.setAttribute('class',`edge ${(selectedIds.has(a.id)||selectedIds.has(b.id))?'active':''} ${fromSide===toSide?'edge-loop':''}`);p.style.pointerEvents='stroke';p.onclick=e=>{e.stopPropagation();askConfirm('Excluir conexão','Deseja remover esta conexão do fluxo?',()=>{record();links.splice(index,1);renderEdges();connections();toast('Conexão removida')})};svg.append(p)});if(connecting){const a=nodes.find(n=>n.id===connecting.from),x=a.x+(connecting.side==='right'?180:0),y=a.y+46,bend=100,p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','edge-preview');p.setAttribute('d',`M ${x} ${y} C ${x+(connecting.side==='right'?bend:-bend)} ${y}, ${connecting.x+(connecting.side==='right'?-65:65)} ${connecting.y}, ${connecting.x} ${connecting.y}`);svg.append(p)}}
function renderMini(){const holder=$('#mini-content');holder.innerHTML='';if(!nodes.length)return;const minX=Math.min(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxX=Math.max(...nodes.map(n=>n.x+180)),maxY=Math.max(...nodes.map(n=>n.y+88)),width=Math.max(1,maxX-minX),height=Math.max(1,maxY-minY),scaleMini=Math.min(108/width,56/height);nodes.forEach(n=>{const el=document.createElement('i');el.className='mini-node '+(selectedIds.has(n.id)?'selected':'');el.style.left=10+(n.x-minX)*scaleMini+'px';el.style.top=23+(n.y-minY)*scaleMini+'px';el.style.width=Math.max(8,180*scaleMini)+'px';el.style.height=Math.max(5,88*scaleMini)+'px';holder.append(el)})}
function select(id,add=false){selectedAnnotation=undefined;$$('.annotation.selected').forEach(x=>x.classList.remove('selected'));if(add){selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);if(!selectedIds.size)selectedIds.add(id)}else selectedIds=new Set([id]);selectedId=id;const n=selected();$('#inspector-title').textContent=n.name;$('#edit-name').value=n.name;$('#edit-description').value=n.desc;$('#state-label').textContent=n.statusLabel;render();connections();prompt();renderLoopInspector(n)}
function connections(){const n=selected(),holder=$('#connection-list');holder.innerHTML='';links.filter(([a,b])=>a===n.id||b===n.id).forEach(([a,b])=>{const other=nodes.find(x=>x.id===(b===n.id?a:b)),el=document.createElement('div');el.className='connection-item';el.innerHTML=`<small>${b===n.id?'DEPENDE DE':'ALIMENTA'}</small><strong>${other?.name||'Etapa removida'}</strong>`;holder.append(el)});if(!holder.children.length)holder.innerHTML='<p class="panel-intro">Nenhuma conexão configurada.</p>'}
function prompt(){const n=selected();$('#prompt-content').textContent=buildPrompt(n)}
function add(item){record();const id='node-'+Date.now();nodes.push({id,name:item[1],desc:item[2],x:390+Math.random()*120,y:440+Math.random()*90,status:'review',statusLabel:'Não configurada'});save();select(id);toast('Bloco adicionado ao canvas')}
function deleteSelected(){if(!selectedIds.size)return;const names=[...selectedIds].map(id=>nodes.find(n=>n.id===id)?.name).filter(Boolean).join(', ');askConfirm('Excluir caixa',`Deseja excluir ${names}? Esta ação não pode ser desfeita.`,()=>{record();const doomed=new Set(selectedIds);nodes=nodes.filter(n=>!doomed.has(n.id));for(let i=links.length-1;i>=0;i--)if(doomed.has(links[i][0])||doomed.has(links[i][1]))links.splice(i,1);selectedIds=new Set();selectedId=nodes[0]?.id;if(selectedId)select(selectedId);else{render();$('#inspector-title').textContent='Nenhuma etapa';$('#state-label').textContent='Adicione uma nova caixa'}save();toast('Caixa(s) excluída(s)')})}
function startNodeDrag(e){if(e.button!==0||e.target.closest('.port'))return;const node=nodes.find(n=>n.id===e.currentTarget.dataset.id);if(!selectedIds.has(node.id))select(node.id,e.shiftKey);record();drag={x:e.clientX,y:e.clientY,positions:[...selectedIds].map(id=>{const n=nodes.find(x=>x.id===id);return{id,x:n.x,y:n.y}})};e.stopPropagation()}
function startConnection(e){const node=e.currentTarget.closest('.node'),side=e.currentTarget.classList.contains('out')?'right':'left';connecting={from:node.dataset.id,side,x:node.offsetLeft+(side==='right'?180:0),y:node.offsetTop+46};e.stopPropagation();toast('Solte sobre a bolinha lateral de outro bloco para conectar')}
function canvasPoint(e){const r=$('#canvas').getBoundingClientRect();return{x:(e.clientX-r.left-pan.x)/scale,y:(e.clientY-r.top-pan.y)/scale}}
function updateMarquee(){const {start,end,box}=marquee,x=Math.min(start.x,end.x),y=Math.min(start.y,end.y),w=Math.abs(end.x-start.x),h=Math.abs(end.y-start.y);Object.assign(box.style,{left:x*scale+pan.x+'px',top:y*scale+pan.y+'px',width:w*scale+'px',height:h*scale+'px'});selectedIds=new Set(nodes.filter(n=>n.x+180>=x&&n.x<=x+w&&n.y+88>=y&&n.y<=y+h).map(n=>n.id));if(selectedIds.size)selectedId=[...selectedIds][0];render()}
function world(){$('#world').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`;$('#zoom-value').textContent=Math.round(scale*100)+'%'}
window.addEventListener('keydown',e=>{const editing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!editing){e.preventDefault();e.shiftKey?redo():undo();return}if(e.code==='Space'&&!editing){spaceDown=true;e.preventDefault()}if((e.key==='Delete'||e.key==='Backspace')&&!editing){e.preventDefault();if(selectedAnnotation)deleteAnnotation(selectedAnnotation);else deleteSelected()}});window.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false});
window.onpointermove=e=>{if(drag){drag.positions.forEach(p=>{const n=nodes.find(x=>x.id===p.id);n.x=Math.max(0,p.x+(e.clientX-drag.x)/scale);n.y=Math.max(0,p.y+(e.clientY-drag.y)/scale)});render()}if(connecting){Object.assign(connecting,canvasPoint(e));renderEdges()}if(marquee){marquee.end=canvasPoint(e);updateMarquee()}if(window.canvasPan){pan.x=window.canvasPan.px+e.clientX-window.canvasPan.x;pan.y=window.canvasPan.py+e.clientY-window.canvasPan.y;world()}};
window.onpointerup=e=>{if(drag){save();drag=null}if(connecting){const port=e.target.closest('.port'),target=port?.closest('.node')?.dataset.id,targetSide=port?.classList.contains('out')?'right':'left';if(target&&target!==connecting.from&&!links.some(([a,b,sa,sb])=>a===connecting.from&&b===target&&sa===connecting.side&&sb===targetSide)){record();links.push([connecting.from,target,connecting.side,targetSide]);select(target);toast('Conexão criada')}else toast('Conexão desfeita');connecting=null;renderEdges()}if(marquee){marquee.box.remove();marquee=null;render()}window.canvasPan=null;$('#canvas').classList.remove('panning')};
$('#canvas').onpointerdown=e=>{if(e.button===1||spaceDown){window.canvasPan={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};$('#canvas').classList.add('panning');return}if(e.button!==0||![ $('#canvas'),$('#world'),$('#edges') ].includes(e.target))return;selectedAnnotation=undefined;$$('.annotation.selected').forEach(x=>x.classList.remove('selected'));const box=document.createElement('div');box.className='selection-box';$('#canvas').append(box);const point=canvasPoint(e);marquee={start:point,end:point,box};selectedIds=new Set();render()};$('#canvas').addEventListener('wheel',e=>{e.preventDefault();if(e.metaKey||e.ctrlKey){scale=Math.max(.55,Math.min(1.45,scale+(e.deltaY<0?.1:-.1)))}else{pan.x-=e.deltaX;pan.y-=e.deltaY}world()},{passive:false});
$('#zoom-in').onclick=()=>{scale=Math.min(1.45,scale+.1);world()};$('#zoom-out').onclick=()=>{scale=Math.max(.55,scale-.1);world()};$('#fit-view').onclick=()=>{scale=.76;pan={x:20,y:22};world();toast('Canvas ajustado')};$('#add-node').onclick=()=>add(catalog[0]);$('#template-btn').onclick=()=>toast('Templates em breve');
$('#node-search').oninput=e=>library($('.category-tabs .active').dataset.filter,e.target.value);$$('.category-tabs button').forEach(b=>b.onclick=()=>{$$('.category-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');library(b.dataset.filter,$('#node-search').value)});$$('.inspector-tabs button').forEach(b=>b.onclick=()=>{$$('.inspector-tabs button').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`[data-panel="${b.dataset.tab}"]`).classList.add('active')});
$('#save-node').onclick=()=>{const n=selected();n.name=$('#edit-name').value.trim()||n.name;n.desc=$('#edit-description').value.trim()||n.desc;n.statusLabel=$('#edit-status').value;n.status=n.statusLabel==='Concluída'?'done':n.statusLabel==='Precisa revisão'?'review':'critical';save();select(n.id);toast('Alterações salvas')};$('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText($('#prompt-content').textContent);toast('Prompt copiado')}catch{toast('Selecione o texto para copiar')}};
$('#export-btn').onclick=()=>$('#export-dialog').showModal();$('.modal-close').onclick=()=>$('#export-dialog').close();$('#download-json').onclick=()=>{const b=new Blob([JSON.stringify({name:'Atlas — SaaS Harness',nodes,links,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='atlas-harness.json';a.click();URL.revokeObjectURL(a.href);$('#export-dialog').close();toast('Harness exportado')};$('#logic-view').onclick=()=>toast('Projeto → Stack → Database → Auth → Pagamentos → Segurança → Teste Final');$('#undo').onclick=()=>toast('Nada para desfazer nesta sessão');$('#redo').onclick=()=>toast('Nada para refazer nesta sessão');$('#close-inspector').onclick=()=>$('.inspector').style.display='none';
$('.priority').textContent='Prioridade ativa';$('.note-1').remove();$('.note-2').remove();$('.brand img').src='logonova.jpg';$('.brand > span:last-child').textContent='MountainLLM';const trash=document.createElement('button');trash.id='delete-nodes';trash.className='delete-nodes';trash.title='Excluir caixa selecionada';trash.setAttribute('aria-label','Excluir caixa selecionada');trash.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m-8 0 1 13h8l1-13M10 11v5m4-5v5"/></svg>';trash.onclick=deleteSelected;$('.inspector-top').append(trash);const inspectorButton=document.createElement('button');inspectorButton.id='open-inspector';inspectorButton.textContent='Propriedades';inspectorButton.onclick=()=>{$('.inspector').style.display='flex'};$('.view-actions').prepend(inspectorButton);$('#canvas .canvas-hint').textContent='Arraste no fundo para selecionar · Dois dedos no trackpad para navegar · Clique e arraste uma bolinha para conectar · Espaço ou botão do meio para navegar';library();render();select(selectedId);world();
$('#open-inspector').style.display='none';$('#close-inspector').onclick=()=>{$('.inspector').style.display='none';$('#open-inspector').style.display='inline-block'};$('#open-inspector').onclick=()=>{$('.inspector').style.display='flex';$('#open-inspector').style.display='none'};

const annotations=document.createElement('div');annotations.id='annotations';$('#world').append(annotations);const drawing=document.createElement('canvas');drawing.id='drawing-layer';drawing.width=2200;drawing.height=1300;$('#world').append(drawing);const drawingContext=drawing.getContext('2d');let drawMode=false,drawingNow=false;
function visiblePoint(){const canvas=$('#canvas'),r=canvas.getBoundingClientRect();return{x:(r.width*.5-pan.x)/scale,y:(r.height*.5-pan.y)/scale}}
function addAnnotation(type,content){record();const point=visiblePoint(),el=document.createElement(type==='image'?'div':'div');el.className=`annotation annotation-${type}`;el.style.left=point.x+'px';el.style.top=point.y+'px';if(type==='image'){const img=document.createElement('img'),handle=document.createElement('button');img.src=content;img.alt='Imagem adicionada ao canvas';handle.className='resize-handle';handle.setAttribute('aria-label','Redimensionar imagem');el.append(img,handle);handle.onpointerdown=startImageResize}else el.textContent=content;makeAnnotationDraggable(el);annotations.append(el)}
function tool(label,handler){const button=document.createElement('button');button.className='canvas-tool';button.textContent=label;button.onclick=handler;$('.view-actions').append(button);return button}
tool('Texto',()=>ask('Adicionar texto','Escreva a anotação',text=>addAnnotation('text',text)));tool('Tag',()=>ask('Adicionar tag','Nome da tag',tag=>addAnnotation('tag',tag)));const drawButton=tool('Desenhar',()=>{drawMode=!drawMode;if(!drawMode)eraserMode=false;drawing.classList.toggle('drawing',drawMode);drawing.classList.toggle('eraser',drawMode&&eraserMode);drawButton.classList.toggle('active',drawMode&&!eraserMode);eraserButton.classList.remove('active');toast(drawMode?'Modo desenho ativado':'Modo desenho desativado')});const eraserButton=tool('Borracha',()=>{eraserMode=!eraserMode;drawMode=eraserMode;drawing.classList.toggle('drawing',drawMode);drawing.classList.toggle('eraser',eraserMode);eraserButton.classList.toggle('active',eraserMode);drawButton.classList.remove('active');toast(eraserMode?'Borracha ativada':'Borracha desativada')});eraserButton.classList.add('eraser-tool');const imageInput=document.createElement('input');imageInput.type='file';imageInput.accept='image/*';imageInput.hidden=true;imageInput.onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>addAnnotation('image',reader.result);reader.readAsDataURL(file)};document.body.append(imageInput);tool('Imagem',()=>imageInput.click());
drawing.onpointerdown=e=>{if(!drawMode)return;record();drawingNow=true;const p=canvasPoint(e);drawingContext.globalCompositeOperation=eraserMode?'destination-out':'source-over';drawingContext.strokeStyle='#f1f1f3';drawingContext.lineWidth=eraserMode?20:2.5;drawingContext.lineCap='round';drawingContext.beginPath();drawingContext.moveTo(p.x,p.y);e.stopPropagation()};drawing.onpointermove=e=>{if(!drawingNow)return;const p=canvasPoint(e);drawingContext.lineTo(p.x,p.y);drawingContext.stroke()};window.addEventListener('pointerup',()=>drawingNow=false);
$('.library-footer button:last-child').onclick=()=>ask('Criar caixa personalizada','Nome da caixa',name=>ask('Criar caixa personalizada','Descrição breve',desc=>{const detail=desc||'Caixa personalizada';catalog.push(['custom',name,detail]);library($('.category-tabs .active').dataset.filter,$('#node-search').value);add(['custom',name,detail])}));

let eraserMode=false,annotationDrag,imageResize;const history=[],future=[];
function snapshot(){return{nodes:structuredClone(nodes),links:structuredClone(links),annotations:annotations.innerHTML,drawing:drawing.toDataURL()}}
function record(){history.push(snapshot());if(history.length>40)history.shift();future.length=0}
function restore(state){nodes=structuredClone(state.nodes);links.splice(0,links.length,...structuredClone(state.links));annotations.innerHTML=state.annotations;annotations.querySelectorAll('.annotation').forEach(el=>{makeAnnotationDraggable(el);el.querySelector('.resize-handle')?.addEventListener('pointerdown',startImageResize)});const image=new Image();image.onload=()=>{drawingContext.clearRect(0,0,drawing.width,drawing.height);drawingContext.drawImage(image,0,0)};image.src=state.drawing;selectedIds=new Set(nodes.slice(0,1).map(n=>n.id));selectedId=nodes[0]?.id;render();if(selectedId)select(selectedId)}
function undo(){if(!history.length){toast('Nada para desfazer');return}future.push(snapshot());restore(history.pop());toast('Ação desfeita')}
function redo(){if(!future.length){toast('Nada para refazer');return}history.push(snapshot());restore(future.pop());toast('Ação refeita')}
function selectAnnotation(el){selectedIds=new Set();selectedId=undefined;$$('.annotation.selected').forEach(x=>x.classList.remove('selected'));selectedAnnotation=el;el.classList.add('selected');render()}
function deleteAnnotation(el){askConfirm('Excluir anotação','Deseja excluir esta anotação?',()=>{record();el.remove();selectedAnnotation=undefined;toast('Anotação excluída')})}
function makeAnnotationDraggable(el){el.onpointerdown=e=>{if(e.button!==0||e.target.closest('.resize-handle'))return;selectAnnotation(el);record();const p=canvasPoint(e);annotationDrag={el,x:p.x-parseFloat(el.style.left),y:p.y-parseFloat(el.style.top)};el.setPointerCapture?.(e.pointerId);e.preventDefault();e.stopPropagation()}}
function startImageResize(e){const el=e.currentTarget.closest('.annotation-image'),width=el.getBoundingClientRect().width;record();imageResize={el,startX:e.clientX,width:width/scale};e.stopPropagation()}
window.addEventListener('pointermove',e=>{if(annotationDrag){const p=canvasPoint(e);annotationDrag.el.style.left=Math.max(0,p.x-annotationDrag.x)+'px';annotationDrag.el.style.top=Math.max(0,p.y-annotationDrag.y)+'px'}if(imageResize){imageResize.el.style.width=Math.max(90,imageResize.width+(e.clientX-imageResize.startX)/scale)+'px'}});window.addEventListener('pointerup',()=>{annotationDrag=null;imageResize=null});
$('#undo').onclick=undo;$('#redo').onclick=redo;

function ask(title,placeholder,onConfirm){const dialog=document.createElement('div');dialog.className='canvas-dialog';dialog.innerHTML=`<form><span>${title}</span><input autocomplete="off" placeholder="${placeholder}"><div><button type="button" data-cancel>Cancelar</button><button type="submit">Adicionar</button></div></form>`;const form=dialog.querySelector('form'),input=dialog.querySelector('input');dialog.querySelector('[data-cancel]').onclick=()=>dialog.remove();form.onsubmit=e=>{e.preventDefault();const value=input.value.trim();if(value){onConfirm(value);dialog.remove()}};document.body.append(dialog);input.focus()}
function askConfirm(title,message,onConfirm){const dialog=document.createElement('div');dialog.className='canvas-dialog confirm-dialog';dialog.innerHTML=`<section><span>${title}</span><p>${message}</p><div><button type="button" data-cancel>Cancelar</button><button type="button" data-confirm>Excluir</button></div></section>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.remove();dialog.querySelector('[data-confirm]').onclick=()=>{onConfirm();dialog.remove()};document.body.append(dialog)}
const inspectorActions=document.createElement('div');inspectorActions.className='inspector-actions';inspectorActions.append($('#close-inspector'),$('#delete-nodes'));$('.inspector-top').append(inspectorActions);

const loopEditor=document.createElement('section');loopEditor.id='loop-editor';loopEditor.className='loop-editor';document.querySelector('[data-panel="config"]').insertBefore(loopEditor,$('#save-node'));
function renderLoopInspector(node){const editor=$('#loop-editor');if(!editor)return;if(node?.id!=='loop'){editor.hidden=true;return}const loop=node.loop||{from:'Teste Final',returnTo:'Security Audit',condition:'existirem falhas críticas',max:3};editor.hidden=false;editor.innerHTML=`<div class="loop-editor-title"><span>COMO ESTE LOOP FUNCIONA</span><small>evita ciclos infinitos</small></div><div class="loop-flow"><div><b>1</b><span>Após</span><strong>${loop.from}</strong></div><i></i><div><b>2</b><span>Repetir</span><strong>${loop.returnTo}</strong></div><i></i><div><b>3</b><span>Sair quando</span><strong>aprovado</strong></div></div><label>Etapa de retorno<select id="loop-return"><option ${loop.returnTo==='Security Audit'?'selected':''}>Security Audit</option><option ${loop.returnTo==='Teste Final'?'selected':''}>Teste Final</option><option ${loop.returnTo==='UI/UX Review'?'selected':''}>UI/UX Review</option></select></label><label>Repetir enquanto<input id="loop-condition" value="${loop.condition}"></label><label>Máximo de ciclos<input id="loop-max" type="number" min="1" max="10" value="${loop.max}"></label><p class="loop-note">Quando o limite for atingido, a etapa é bloqueada e solicita revisão manual.</p>`;editor.querySelectorAll('input,select').forEach(input=>input.onchange=()=>{record();node.loop={from:'Teste Final',returnTo:editor.querySelector('#loop-return').value,condition:editor.querySelector('#loop-condition').value||'existirem falhas críticas',max:Math.max(1,Math.min(10,Number(editor.querySelector('#loop-max').value)||3))};render();renderLoopInspector(node);save();toast('Loop atualizado')})}
select(selectedId);

var promptSpecialists={
  'Projeto':'Transforme a intenção do produto em uma especificação verificável. Defina problema, público, jornada principal, escopo do MVP, regras de negócio, métricas de sucesso, riscos e decisões que precisam de aprovação. Mapeie ambiguidades como perguntas objetivas antes de escrever código.',
  'Stack':'Projete uma arquitetura coerente com o repositório existente. Justifique cada tecnologia, fronteiras de responsabilidade, convenções de pastas, contratos entre camadas, variáveis de ambiente, estratégia de erros, observabilidade e plano de migração. Nunca introduza dependências sem necessidade ou altere áreas fora do escopo.',
  'Database':'Modele entidades, relacionamentos, chaves, índices, constraints, migrations e políticas de acesso. Verifique consistência de tipos entre banco, backend e frontend. Aplique menor privilégio, validação de entrada, RLS quando aplicável, seeds reproduzíveis, rollback e consultas eficientes.',
  'Autenticação':'Implemente autenticação e autorização por camadas. Proteja sessões, tokens, cookies, recuperação de senha, verificação de e-mail, rate limit e rotas privadas. Diferencie identidade, papéis e permissões. Não exponha secrets e teste sucesso, expiração, acesso indevido e recuperação.',
  'Pagamentos':'Integre pagamentos com segurança operacional: variáveis de ambiente, produtos, preços, status de assinatura, webhooks autenticados, idempotência, retries e reconciliação. Separe sandbox e produção. Nunca confie no cliente para confirmar cobrança; trate cancelamentos, falhas e upgrades.',
  'Dashboard':'Construa uma experiência clara para tarefas recorrentes. Defina hierarquia, estados vazios, carregamento, erro, responsividade, acessibilidade e feedback de ações. Reutilize componentes, preserve consistência visual e valide o fluxo em desktop e mobile com dados realistas.',
  'Security Audit':'Audite autenticação, autorização, segredos, input validation, injeção, XSS, CSRF, CORS, sessões, uploads, banco, dependências, logs e configuração. Classifique cada achado por impacto e evidência. Corrija riscos críticos, execute testes de regressão e não marque aprovado sem prova objetiva.',
  'UI/UX Review':'Revise hierarquia, legibilidade, contraste, espaçamento, tipografia, navegação, foco, teclado, responsividade, mensagens, loading, empty states e recuperação de erros. Encontre inconsistências entre telas e proponha correções pequenas, mensuráveis e alinhadas à intenção do produto.',
  'Teste Final':'Execute validação real de ponta a ponta: iniciar aplicação, autenticar, navegar, criar e alterar dados, testar APIs, persistência, console, responsividade, fluxos de falha e regressão. Produza relatório com ambiente, passos, resultado esperado, evidência, bloqueios e decisão APROVADO/REPROVADO.',
  'Loop de qualidade':'Orquestre uma iteração limitada de correção. Use o resultado da etapa de teste como entrada, envie os achados ao responsável pela correção, retorne para auditoria e só encerre quando a condição de aprovação for atendida ou o máximo de ciclos for atingido. Registre cada ciclo e evite mudanças não relacionadas.'
};
function buildPrompt(node){const specialist=promptSpecialists?.[node.name]||'Estruture esta etapa como um módulo independente, com entradas, ações, ferramentas, dependências, riscos, critérios de aceitação e evidências de conclusão.';return `PAPEL: Você é o agente especialista responsável pela etapa “${node.name}” do Harness MountainLLM.\n\nMISSÃO\n${specialist}\n\nCONTEXTO OBRIGATÓRIO\n1. Leia o Harness e identifique as etapas anteriores concluídas, dependências bloqueadas e anotações de IA.\n2. Preserve a arquitetura, convenções e decisões já aprovadas. Não reescreva partes não relacionadas.\n3. Antes de mudar código, declare o plano curto, arquivos previstos, riscos e critérios de verificação.\n4. Use ferramentas reais disponíveis para inspecionar, implementar e validar. Nunca declare sucesso sem evidência.\n\nPROTOCOLO DE EXECUÇÃO\n- Trabalhe em alterações pequenas, reversíveis e consistentes.\n- Valide entradas, trate erros explicitamente e mantenha secrets somente em variáveis de ambiente.\n- Atualize documentação, tipos, testes e estados dependentes sempre que a mudança exigir.\n- Se houver conflito de requisito, pare e registre a pergunta com opções e impacto.\n- Ao detectar alteração estrutural, invalide etapas dependentes e registre o motivo no histórico.\n\nFORMATO DE SAÍDA\nEntregue: (1) resumo do que foi feito, (2) arquivos/áreas afetadas, (3) comandos e testes executados, (4) resultados observados, (5) riscos ou pendências, (6) estado recomendado da etapa e (7) evidências para auditoria.\n\nCRITÉRIO DE CONCLUSÃO\nA etapa só pode ser marcada como concluída quando suas dependências estiverem satisfeitas, os critérios configurados tiverem sido verificados e nenhum problema crítico relacionado permanecer aberto.`}
const dictionary={
  pt:{Properties:'Propriedades',Text:'Texto',Tag:'Tag',Draw:'Desenhar',Eraser:'Borracha',Image:'Imagem',Settings:'Configuração',Prompt:'Prompt',Connections:'Conexões',History:'Histórico',Save:'Salvar alterações',Library:'BIBLIOTECA',Harness:'Blocos do Harness'},
  en:{Properties:'Properties',Text:'Text',Tag:'Tag',Draw:'Draw',Eraser:'Eraser',Image:'Image',Settings:'Configuration',Prompt:'Prompt',Connections:'Connections',History:'History',Save:'Save changes',Library:'LIBRARY',Harness:'Harness blocks'},
  es:{Properties:'Propiedades',Text:'Texto',Tag:'Etiqueta',Draw:'Dibujar',Eraser:'Borrador',Image:'Imagen',Settings:'Configuración',Prompt:'Prompt',Connections:'Conexiones',History:'Historial',Save:'Guardar cambios',Library:'BIBLIOTECA',Harness:'Bloques del Harness'},
  zh:{Properties:'属性',Text:'文本',Tag:'标签',Draw:'绘制',Eraser:'橡皮擦',Image:'图片',Settings:'配置',Prompt:'提示词',Connections:'连接',History:'历史记录',Save:'保存更改',Library:'库',Harness:'Harness 模块'}
};
function translateInterface(){const t=dictionary[language];$('#open-inspector').textContent=t.Properties;$$('.canvas-tool').forEach(button=>{const original=button.dataset.key||button.textContent.trim();button.dataset.key=original;const key={Texto:'Text',Tag:'Tag',Desenhar:'Draw',Borracha:'Eraser',Imagem:'Image'}[original]||original;button.textContent=t[key]||original});$$('.inspector-tabs button').forEach(button=>{const original=button.dataset.key||button.textContent.trim();button.dataset.key=original;const key={Configuração:'Settings',Prompt:'Prompt',Conexões:'Connections',Histórico:'History'}[original]||original;button.textContent=t[key]||original});$('.save-button')&&( $('.save-button').textContent=t.Save);$('.library-header .eyebrow')&&($('.library-header .eyebrow').textContent=t.Library);$('.library-header h2')&&($('.library-header h2').textContent=t.Harness);prompt()}
const languageSelect=document.createElement('select');languageSelect.className='language-select';languageSelect.innerHTML='<option value="pt">PT</option><option value="en">EN</option><option value="es">ES</option><option value="zh">中文</option>';languageSelect.value=language;languageSelect.onchange=()=>{language=languageSelect.value;localStorage.setItem('mountain-language',language);translateInterface();toast('Idioma atualizado')};$('#export-btn').insertAdjacentElement('afterend',languageSelect);translateInterface();
const toolsDock=document.createElement('div');toolsDock.className='canvas-tools-dock';toolsDock.setAttribute('aria-label','Ferramentas do canvas');toolsDock.innerHTML='<span>FERRAMENTAS</span>';$$('.canvas-tool').forEach(button=>toolsDock.append(button));$('.canvas-area').insertBefore(toolsDock,$('#canvas'));languageSelect.style.display='inline-block';
$('.project-title strong').remove();$('.project-title .chevron').remove();const topActions=$('.top-actions'),share=[...topActions.querySelectorAll('button')].find(button=>button.textContent.trim()==='Compartilhar'),exportButton=$('#export-btn'),publishButton=$('.publish'),profile=$('.avatar');$('#undo').remove();$('#redo').remove();topActions.querySelector('i')?.remove();topActions.append(share,exportButton,publishButton,languageSelect,profile);
